sonar.projectKey=ihsan-ramadhan_tuck
sonar.organization=ihsan-ramadhan

# Exclude generated code and external dependencies from analysis
sonar.exclusions=gui/frontend/wailsjs/**,gui/frontend/dist/**,gui/frontend/node_modules/**,build/**
