// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetRulesPath() {
  return window['go']['main']['App']['GetRulesPath']();
}

export function GetSchedules() {
  return window['go']['main']['App']['GetSchedules']();
}

export function RunOrganize(arg1, arg2) {
  return window['go']['main']['App']['RunOrganize'](arg1, arg2);
}

export function SaveRules(arg1) {
  return window['go']['main']['App']['SaveRules'](arg1);
}

export function SaveSchedule(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSchedule'](arg1, arg2, arg3, arg4);
}

export function StartSchedule(arg1) {
  return window['go']['main']['App']['StartSchedule'](arg1);
}

export function StopSchedule(arg1) {
  return window['go']['main']['App']['StopSchedule'](arg1);
}

export function UndoRun(arg1) {
  return window['go']['main']['App']['UndoRun'](arg1);
}

export function ValidateRules(arg1) {
  return window['go']['main']['App']['ValidateRules'](arg1);
}
