// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {history} from '../models';
import {main} from '../models';

export function DeleteSchedule(arg1:string):Promise<void>;

export function GetHistory():Promise<Array<history.Run>>;

export function GetRules():Promise<string>;

export function GetRulesPath():Promise<string>;

export function GetSchedules():Promise<Array<main.scheduleView>>;

export function RunOrganize(arg1:Array<string>,arg2:boolean):Promise<Array<main.runResult>>;

export function SaveRules(arg1:string):Promise<void>;

export function SaveSchedule(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<void>;

export function StartSchedule(arg1:string):Promise<void>;

export function StopSchedule(arg1:string):Promise<void>;

export function UndoRun(arg1:number):Promise<number>;

export function ValidateRules(arg1:string):Promise<string>;
